In [1]:
# 1) Numpy
# 2) Pandas
# 3) Matplotlib

In [ ]:
1) Numpy --> Numarical Python


    # Python ----> 1991

Numpy --> 2005

    # Travis Oliphant

Python

1) List     2) tuple    3) set    4) dect

# zx = [1, 12, "helo", True, 10.8]


# Array -> c, java, javascript.....


# Numpy --------> Arrays

1) List ---> hittrogenoious type of data.

2) Numpy:

Array --> array is a data structure,that store homogenious (same type of data) type of data in congeious 
        # memory location

2) Array --> 
    70%  ---> python
    30% ---> C/C++

numpy array ----> 50x  ----> list


In [2]:
# numpy -----> arrays

In [3]:
# installtion

!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [6]:
# numpy --> help to create ndarrays

In [7]:
# ndarray ----> n - demetional arrays

##### ndarray --> when we create an object in numpy with the help of array method, that object is called ndarray.

In [8]:
arr = np.array(10)

In [9]:
type(arr)

numpy.ndarray

In [10]:
a = 10
type(a)

int

In [11]:
arr1 = np.array([12, 34, 45, 56])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
# Arrays ---- > dimensions

# 1 - D
# 2 - D Arrays
# 3 - D array
# .
# .
#     .
# n - d arrays

In [ ]:
# Numpy Attributes
    1) ndim --> n-dimensions
            it returns the dimensions of an ndarry 

    2) shape --> 
            it returns the shape of an ndarrays

In [14]:
# 0 - D Array

In [15]:
arr = np.array(10)

In [16]:
arr

array(10)

In [17]:
arr.shape

()

In [18]:
arr.ndim

0

In [19]:
# 1-D Array  ---> store multiple elements

In [20]:
arr3 = np.array([12, 34, 45, 67, 23])

In [21]:
arr3

array([12, 34, 45, 67, 23])

In [22]:
arr3.ndim

1

In [23]:
arr3.shape

# shape --> it always return a tuple

(5,)

In [26]:
# x = (10, )

# type(x)

In [27]:
# 2-D nArrays : 2-d ndarray is the combination of mutiple 1-D Ndarays.

In [32]:
arr4 = np.array([[12, 34, 45, 67, 8], [12, 34, 45, 23, 45]])

In [33]:
arr4

array([[12, 34, 45, 67,  8],
       [12, 34, 45, 23, 45]])

In [34]:
arr4.ndim

2

In [35]:
arr4.shape

(2, 5)

In [36]:
arr4 = np.array([[12, 34, 45, 67, 8], [12, 34, 45, 23, 45], [23, 45, 56, 34, 23]])

In [37]:
arr4

array([[12, 34, 45, 67,  8],
       [12, 34, 45, 23, 45],
       [23, 45, 56, 34, 23]])

In [38]:
arr4.ndim

2

In [39]:
arr4.shape

(3, 5)

In [40]:
# 3-D array --> is the combination of multiple 2-D ndarrays.

In [50]:
arr5 = np.array([[[12, 23, 34], [45, 3, 23]], [[34, 45, 56], [56, 23, 23]]])

In [51]:
arr5

array([[[12, 23, 34],
        [45,  3, 23]],

       [[34, 45, 56],
        [56, 23, 23]]])

In [52]:
arr5.ndim

3

In [53]:
arr5.shape

(2, 2, 3)

In [ ]:
4-D
...
.
.
.
.
..
10-D