In [ ]:
# Numpy

# 12 : 1 => Machine Leaning
# 1 : 2 => Numpy

In [1]:
# Numpy

In [2]:
# numpy --> mutable
#     1) replace

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 4, 5, 6, 7])

In [6]:
# type(arr)

In [7]:
# element replacement
# ojenamtname[indxnumber] = newelemnt

In [8]:
arr[2] = 500

In [9]:
arr

array([  1,   2, 500,   4,   5,   4,   5,   6,   7])

In [11]:
# adding elements
# append()

arr = np.array([1, 2, 3, 4, 5, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 4, 5, 6, 7])

In [15]:
# a = 100

In [13]:
a = 30

In [14]:
a

30

In [18]:
# adding elements
# append()

arr = np.array([1, 2, 3, 4, 5, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 4, 5, 6, 7])

In [17]:
# append() ----> it add element at the end

# np.append(objectname, newelemnt)

In [21]:
xyz = np.append(arr, 100)

In [22]:
xyz

array([  1,   2,   3,   4,   5,   4,   5,   6,   7, 100])

In [25]:
arr = np.array([1, 2, 3, 4, 5, 4, 5, 6, 7])
# arr

In [29]:
xyz = np.append(arr, [100, 400, 300])
xyz

array([  1,   2,   3,   4,   5,   4,   5,   6,   7, 100, 400, 300])

In [30]:
# insert() ----> add new element at a perticuler location.

# syntex in numpy

# np.insert(objectname, indexnumber, newelelement)

In [32]:
arr = np.array([1, 2, 3, 4, 5, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 4, 5, 6, 7])

In [33]:
np.insert(arr, 1, 100)

array([  1, 100,   2,   3,   4,   5,   4,   5,   6,   7])

In [34]:
# np.append()
# np.insert()

In [35]:
# question:

# 1) create a emptly ndarray
# 2) add table of 2 in that ndarray

# # output
# np.array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6' ..... '2 x 10 = 20'])


# np.array([2, 4, 5, 6, 7, 8, 9, 10])

In [36]:
# arange()

np.arange(2, 11, 1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
xy = np.array([])

for i in range(1, 11):
    h = f"2 x {i} = {2*i}"
    xy = np.append(xy, h)

In [47]:
xy

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U32')

In [48]:
# replace
# add new elements
#     append()
#     insert()
# remove elements

In [49]:
arr = np.array([1, 2, 3, 4, 5, 4, 5, 6, 7])

inx = [2, 4, 6]
eleme = [100, 200, 300]

In [50]:
np.insert(arr, inx, eleme)

array([  1,   2, 100,   3,   4, 200,   5,   4, 300,   5,   6,   7])

In [55]:
# remove elements

xyz = np.array([1, 3, 4, 6, 3, 4, 5, 3, 300, 23])

In [54]:
# np.delete(objectname, indexnumber)

In [58]:
x = np.delete(xyz, -2)

In [59]:
x

array([ 1,  3,  4,  6,  3,  4,  5,  3, 23])

In [60]:
xyz = np.array([1, 3, 4, 6, 3, 4, 5, 3, 300, 23])

In [61]:
inx = [1, 5, -2]

In [62]:
np.delete(xyz, inx)

array([ 1,  4,  6,  3,  5,  3, 23])

In [63]:
# reshape()

# random

In [64]:
# reshape() ---> it help us to chnage the dimennsions of the ndaary

# model

In [65]:
# 1-D ---- 2-D

In [66]:
x = np.array([1, 2, 3, 2, 3, 2, 3, 4, 4, 5, 6, 7, 5, 4])

In [67]:
len(x)

14

In [68]:
x.ndim

1

In [69]:
# 2-D

In [70]:
# np.reshape(objename, size)

In [71]:
x = np.array([1, 2, 3, 2, 3, 2, 3, 4, 4, 5, 6, 7, 5, 4])

In [74]:
np.reshape(x, (2, 7))

array([[1, 2, 3, 2, 3, 2, 3],
       [4, 4, 5, 6, 7, 5, 4]])

In [76]:
u = np.reshape(x, (7, 2))

In [77]:
u.shape

(7, 2)

In [78]:
u

array([[1, 2],
       [3, 2],
       [3, 2],
       [3, 4],
       [4, 5],
       [6, 7],
       [5, 4]])

In [79]:
# 1-3d

In [88]:
xy = np.arange(1, 19)

In [89]:
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [90]:
len(xy)

18

In [91]:
np.reshape(xy, (3, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [93]:
# -1 ---> automatically

In [101]:
x = np.arange(1, 13)

In [102]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
np.reshape(x, (4, -1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [107]:
np.reshape(x, (-1, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
# 2D -- 1D

In [109]:
zx = np.array([[12, 34, 45, 56], [45, 34, 56, 4]])

In [111]:
zx

array([[12, 34, 45, 56],
       [45, 34, 56,  4]])

In [113]:
# 1-D 

np.reshape(zx, -1)

array([12, 34, 45, 56, 45, 34, 56,  4])

In [114]:
zx.reshape(-1)

array([12, 34, 45, 56, 45, 34, 56,  4])