In [1]:
# Numpy:
# Numpy
# ndim
# shape
# ndarryas
# indexing
# slicing

In [ ]:
where() ----> return indexnuber of a perticuler element from the ndarray.

In [2]:
import numpy as np

In [3]:
arr = np.array([12, 34, 45, 23, 12, 34, 56, 768, 89, 90, 67, 56])

In [6]:
# arr[1]

In [11]:
# np.where(objectname operator element)

# np.where(arr, 768)

compersion operators:

# 1) ==
# 2) !=
# 3) >
# 4) <
# 5) <=
# 6) >=

In [12]:
# help(np.where)

In [16]:
# 10 != 11

In [17]:
arr = np.array([12, 34, 45, 23, 12, 34, 56, 768, 89, 90, 67, 56])

In [18]:
np.where(arr == 768)

(array([7], dtype=int64),)

In [19]:
np.where(arr == 12)

(array([0, 4], dtype=int64),)

In [20]:
arr = np.array([12, 34, 45, 23, 12, 34, 56, 768, 89, 90, 67, 56])

In [21]:
np.where(arr > 50)

(array([ 6,  7,  8,  9, 10, 11], dtype=int64),)

In [22]:
# where() ---> location/ indexnumber return

In [23]:
arr = np.array([12, 34, 45, 23, 12, 34, 56, 768, 89, 90, 67, 56])

In [25]:
np.where(arr != 34)

(array([ 0,  2,  3,  4,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [26]:
# indexing:

In [27]:
arr = np.array([12, 34, 45, 23, 12, 34, 56, 768, 89, 90, 67, 56])

In [28]:
arr[2]

45

In [29]:
# sort()  --> aranding data in order

In [30]:
x = np.array([12, 3, 4, 6, 3, 2, 4])

In [32]:
y = np.sort(x)
y

array([ 2,  3,  3,  4,  4,  6, 12])

In [33]:
y[: : -1]

array([12,  6,  4,  4,  3,  3,  2])

In [34]:
# arange()
    # to genrate data

# python ---> range()  numpy -----> arange()

In [35]:
# newarr = np.arange(start, end, increment)

newarr = np.arange(1, 21)

In [36]:
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
newarr = np.arange(10, 50, 2)
newarr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [40]:
# where()
# sort()
# arange()

In [41]:
# ones() ----> 

In [ ]:
# np.ones(size)

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [44]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.ones((8, 9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [47]:
# zeros()

In [48]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
np.zeros((3, 4, 6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [52]:
# dignal mertix

In [53]:
# eye()


In [55]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
# where()
# sort()
# arange()
# ones()
# zeros()
# eye()


In [57]:
# list -> mutable

# ndarrays --> mutable
    # 1) adding elements
    # 2) replace elements
    # 3) update elemets
    # 4) delete elements

In [58]:
xyz = np.array([12, 34, 45, 67, 34])

In [59]:
# replace elements

In [61]:
# syntex:
    # objectname[indexnumber] = newelement

In [62]:
xyz[1] = 100

In [63]:
xyz

array([ 12, 100,  45,  67,  34])

In [64]:
xy = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [66]:
xy[-2] = 90

In [67]:
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8, 90, 10])

In [68]:
xy = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [71]:
inx = [1, 4, 9]
new_elements = [200, 500, 900]

xy[inx] = new_elements

In [72]:
xy

array([  1, 200,   3,   4, 500,   6,   7,   8,   9, 900])

In [73]:
xy[[1, 4, 9]] = [200, 500, 900]

In [74]:
xy

array([  1, 200,   3,   4, 500,   6,   7,   8,   9, 900])