In [1]:
# Numpy --> numariacal python

In [ ]:
intro
arrays
numpy --- list
ndarrays
build
    1-D ndarray
    2-D ndarray
    3-D ndarray
Attributes:
    1) Shape
    2) ndim

In [2]:
import numpy as np

### Indexing or Slicing

In [3]:
# indexing ---> get single element
# slicing ----> piece of data

In [4]:
# 1-D ndarray --> indexing slicing

In [5]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [6]:
arr

array([12, 34, 45, 56, 34, 45, 67, 78,  5,  6,  8, 45,  3])

In [7]:
arr.ndim

1

In [8]:
arr.shape

(13,)

In [9]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [ ]:
# indexing:
#     syntex:

objectname[inedxnumebr]

In [10]:
arr[2]

45

In [11]:
arr[6]

67

In [12]:
# negtive indeixng

In [13]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [14]:
arr[-3]

8

In [15]:
arr[10]

8

In [16]:
# Slicing:
    # list, range()


In [17]:
# objectname[start_index_number : end_index_number : increment(steps)]

# default values:
#     start_index_number = 0
#     end_index_number = n - 1
#                     n  = totle number of elements
#     indecreamnt = 1

In [18]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [20]:
x = arr[4 : 9 : 1]
x

array([34, 45, 67, 78,  5])

In [21]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [23]:
arr[1 : 6 : 1]

array([34, 45, 56, 34, 45])

In [24]:
arr[1 : 6 : 1]

array([34, 45, 56, 34, 45])

In [25]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [26]:
arr[4 : ]

array([34, 45, 67, 78,  5,  6,  8, 45,  3])

In [27]:
arr[ : 6]

array([12, 34, 45, 56, 34, 45])

In [32]:
arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [31]:
arr[0 : 8 : 2]

array([12, 45, 34, 67])

In [34]:
arr[: : 3]

array([12, 56, 67,  6,  3])

In [35]:

arr = np.array([12, 34, 45, 56, 34, 45, 67, 78, 5, 6, 8, 45, 3])

In [36]:
# reverse

arr[: : -1]

array([ 3, 45,  8,  6,  5, 78, 67, 45, 34, 56, 45, 34, 12])

In [37]:
# 2-D ndarray --> indexing or slicing

In [43]:
arr = np.array([[12, 23, 34, 45, 676, 45, 34, 23], [34, 5, 34, 23, 45, 23, 345, 23]])

In [44]:
arr

array([[ 12,  23,  34,  45, 676,  45,  34,  23],
       [ 34,   5,  34,  23,  45,  23, 345,  23]])

In [45]:
arr.ndim

2

In [46]:
arr.shape

(2, 8)

In [47]:
arr = np.array([[12, 23, 34, 45, 676, 45, 34, 23], [34, 5, 34, 23, 45, 23, 345, 23]])

In [49]:
# syntex : indexing

# objectname[array_number][elemt_index_number]

arr[0][4]

676

In [50]:
arr[1][6]

345

In [51]:
arr[1][-2]

345

In [52]:
xyz = np.array([[23, 4, 45, 45], [45, 3, 34, 23], [8, 9, 6, 5], [23, 4, 23, 2]])

In [53]:
xyz

array([[23,  4, 45, 45],
       [45,  3, 34, 23],
       [ 8,  9,  6,  5],
       [23,  4, 23,  2]])

In [54]:
xyz.shape

(4, 4)

In [55]:
xyz = np.array([[23, 4, 45, 45], [45, 3, 34, 23], [8, 9, 6, 5], [23, 4, 23, 2]])

In [58]:
xyz[3][-1]

2

In [59]:
# slicng

In [60]:
xyz = np.array([[23, 4, 45, 45], [45, 3, 34, 23], [8, 9, 6, 5], [23, 4, 23, 2]])

In [62]:
xyz[1][1 : ]

array([ 3, 34, 23])

In [63]:
# 3-D ndarray --- indexing / slicing

In [64]:
arr3 = np.array([[[12, 23, 4, 2], [45, 56, 3, 4]], [[45, 34, 45, 34], [45, 34, 45, 2]]])

In [65]:
arr3

array([[[12, 23,  4,  2],
        [45, 56,  3,  4]],

       [[45, 34, 45, 34],
        [45, 34, 45,  2]]])

In [66]:
arr3.shape

(2, 2, 4)

In [67]:
arr3.ndim

3

In [68]:
arr3 = np.array([[[12, 23, 4, 2], [45, 56, 3, 4]], [[45, 34, 45, 34], [45, 34, 45, 2]]])

In [71]:
arr3[0][1][2]

3

In [75]:
arr3[1][1][-1]

2

In [79]:
arr3[0][0][1 : ]

array([23,  4,  2])