In [1]:
import numpy as np

In [2]:
# mutable:

In [3]:
zx = np.array([12, 56, 34, 23, 12, 56, 78, 100])

In [ ]:
# replace krna hai....

In [6]:
zx[2] = 500

In [7]:
zx

array([ 12,  56, 500,  23,  12,  56,  78, 100])

In [8]:
zx[0] = 1

In [9]:
zx

array([  1,  56, 500,  23,  12,  56,  78, 100])

In [11]:
zx[1] = 78

In [12]:
zx

array([  1,  78, 500,  23,  12,  56,  78, 100])

In [13]:
zx[0] = 78

In [14]:
zx

array([ 78,  78, 500,  23,  12,  56,  78, 100])

In [15]:
zx[0] = 9000

In [22]:
x = np.append(zx, 1000)

In [23]:
x

array([   2,    5,    1,    6,    3,    8,   10, 1000, 1000])

In [24]:
x = np.array([45, 34, 23, 10])

In [26]:
np.append(x, [12, 34, 100])

array([ 45,  34,  23,  10,  12,  34, 100])

In [27]:
# insert()

In [28]:
x

array([45, 34, 23, 10])

In [29]:
np.insert(x, 1, 2000)

array([  45, 2000,   34,   23,   10])

In [30]:
np.insert(x, [1, 3, 4, 2], [20, 455, 56, 23])

array([ 45,  20,  34,  23,  23, 455,  10,  56])

In [31]:
zx = np.array([1, 2, 3, 4, 5, 6, 7])

In [32]:
y = np.insert(zx, 2, 20)

In [33]:
y

array([ 1,  2, 20,  3,  4,  5,  6,  7])

In [34]:
zx

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
tk = np.insert(zx, [1, 3], [100, 200])

In [37]:
tk

array([  1, 100,   2,   3, 200,   4,   5,   6,   7])

In [38]:
tk[4] = 95

In [39]:
tk

array([  1, 100,   2,   3,  95,   4,   5,   6,   7])

In [44]:
np.delete(tk, [1, 3])

array([ 1,  2, 95,  4,  5,  6,  7])

In [ ]:
['2 x 1 = 2', '2 x 2 = 4', .......]

In [73]:
table = np.array(["car"])

In [74]:
for i in range(1, 11):
    table = np.append(table, f"2 x {i} = {2 * i}")

In [75]:
table

array(['car', '2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8',
       '2 x 5 = 10', '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16',
       '2 x 9 = 18', '2 x 10 = 20'], dtype='<U11')

In [76]:
np.delete(table, 0)

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U11')

In [ ]:
if 2 % i != 0:

In [ ]:
[1, 2, 333, 4, 55555, 6, 7777777, 8, 999999999, 10]

In [98]:
3 * "3"

'333'

In [83]:
s = np.array([1])

In [84]:
for i in range(1, 11):
    if i % 2 == 0:
        s = np.append(s, i)
    else:
        s = np.append(s, f"{i}" * i)

In [85]:
s

array(['1', '1', '2', '333', '4', '55555', '6', '7777777', '8',
       '999999999', '10'], dtype='<U11')

In [91]:
zx = np.array(s, dtype = int)

In [94]:
pq = np.delete(zx, 1)

zx

array([        1,         1,         2,       333,         4,     55555,
               6,   7777777,         8, 999999999,        10])

In [95]:
pq

array([        1,         2,       333,         4,     55555,         6,
         7777777,         8, 999999999,        10])