# Numpy random

In [2]:
from numpy import random
import numpy as np

In [3]:
# import random

In [4]:
zx = random.randint(100)

In [5]:
zx

87

In [6]:
random.rand()

0.6917497186064298

In [7]:
zx = random.randint(100, size = (7))

In [8]:
zx

array([29, 41, 33, 15, 75, 54, 91])

In [9]:
zx = random.randint(100, size = (7, 3))

In [10]:
zx

array([[16, 93, 51],
       [50, 63, 47],
       [23, 70, 58],
       [42, 33, 91],
       [50, 47, 59],
       [87, 40, 41],
       [82, 96, 87]])

In [11]:
random.rand()

0.17095857827373417

In [12]:
random.rand()

0.1782327193992117

In [13]:
zx = []
for i in range(1, 10):
    zx.append(random.rand())

In [14]:
np.array(zx)

array([0.08473088, 0.67248404, 0.18858398, 0.48805654, 0.91271816,
       0.98442404, 0.89094126, 0.83589015, 0.79408677])

In [15]:
x = random.choice([12, 45, 34, 23, 56, 34, 78, 34, 100], size = (10, 4, 6))

In [16]:
x

array([[[ 12,  34,  12,  12,  34, 100],
        [100,  56,  78,  34,  12,  45],
        [ 34,  34,  34,  34,  45, 100],
        [ 23,  78, 100,  34,  78,  34]],

       [[ 34,  34,  23,  45, 100,  12],
        [ 12,  34,  34,  78,  45,  34],
        [ 45, 100,  45,  34,  45, 100],
        [ 12,  34,  34,  12,  56,  34]],

       [[ 12,  23,  34,  34,  23,  34],
        [100,  12,  34,  56,  34,  34],
        [ 45, 100,  34,  34,  23,  12],
        [ 23,  12,  56, 100,  56,  45]],

       [[ 23, 100,  34,  78,  56,  78],
        [ 34,  23,  34,  34,  56,  34],
        [ 12,  34,  34,  56,  23,  23],
        [ 34,  12,  23,  56,  45,  34]],

       [[ 45,  23,  34,  34,  34,  56],
        [ 12, 100,  34,  34,  56,  56],
        [ 34,  34, 100,  56,  23, 100],
        [ 78,  12,  34,  34,  78,  56]],

       [[ 34,  56,  12,  23,  12,  34],
        [ 12,  34,  45,  23,  45,  34],
        [ 34,  12,  34,  34,  34,  56],
        [ 56,  34,  23,  34,  34,  34]],

       [[ 34,  34,  12,  78,

In [17]:
random
randint
rand
choice

NameError: name 'randint' is not defined

In [18]:
x = [23, 4, 12, 34, 12, 45, 23, 100]


print(random.shuffle(x))

None


In [20]:
help(random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)

    Modify a sequence in-place by shuffling its contents.

    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.

    .. note::
        New code should use the `~numpy.random.Generator.shuffle`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.

    Returns
    -------
    None

    See Also
    --------
    random.Generator.shuffle: which should be used for new code.

    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random

    Multi-dimensional arrays are only shuffled along the first axis:

 

In [26]:
x = [12, 23, 34, 67, 45, 34]

In [27]:
random.shuffle(x)

In [28]:
x

[67, 23, 34, 12, 34, 45]

In [ ]:
# arrange(start, end, increment)


# range()

# start = 0
# end = n - 1
# increment = 1

In [32]:
zx = np.arange(2, 20, 2)

In [34]:
zx.reshape(3, 3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])