In [1]:
import numpy as np

In [2]:
zx = np.arange(2, 20)

In [3]:
zx

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
len(zx)

18

In [4]:
zx.ndim

1

In [6]:
xy = zx.reshape(6, 3)

In [7]:
xy

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
# random:

In [8]:
from numpy import random

In [27]:
random.randint(50, 90, size = (6, 5))

array([[81, 74, 62, 51, 52],
       [86, 78, 58, 57, 62],
       [82, 82, 54, 53, 67],
       [70, 67, 71, 64, 79],
       [66, 74, 78, 81, 63],
       [77, 76, 52, 82, 50]])

In [41]:
random.rand(12, 2)

array([[0.33451397, 0.32055109],
       [0.89490081, 0.83651882],
       [0.60235346, 0.2560191 ],
       [0.9388228 , 0.35037405],
       [0.99553228, 0.78911116],
       [0.75837527, 0.93618558],
       [0.12808799, 0.58402531],
       [0.84624967, 0.39740279],
       [0.81468254, 0.44161896],
       [0.84682859, 0.08891677],
       [0.51144692, 0.28284996],
       [0.21291571, 0.65298544]])

In [43]:
zx = []

for i in range(1, 21):
    zx.append(random.rand())

In [44]:
zx

[0.6971458025934539,
 0.4763883853687423,
 0.948652071955328,
 0.9415437091726907,
 0.9503006461067497,
 0.7413740069262023,
 0.5842894369190679,
 0.562528483761879,
 0.5301700698328896,
 0.5438513552965448,
 0.2298186165167979,
 0.54572939814155,
 0.5579899156384188,
 0.23662285682870976,
 0.9708751074650506,
 0.4994178164617349,
 0.022584346670184385,
 0.7805895315699857,
 0.3595665632034558,
 0.7816209941940641]

In [45]:
type(zx)

list

In [46]:
xz = np.array(zx)

In [47]:
type(xz)

numpy.ndarray

In [48]:
xz

array([0.6971458 , 0.47638839, 0.94865207, 0.94154371, 0.95030065,
       0.74137401, 0.58428944, 0.56252848, 0.53017007, 0.54385136,
       0.22981862, 0.5457294 , 0.55798992, 0.23662286, 0.97087511,
       0.49941782, 0.02258435, 0.78058953, 0.35956656, 0.78162099])

In [49]:
len(xz)

20

In [50]:
xz.reshape(5, 4)

array([[0.6971458 , 0.47638839, 0.94865207, 0.94154371],
       [0.95030065, 0.74137401, 0.58428944, 0.56252848],
       [0.53017007, 0.54385136, 0.22981862, 0.5457294 ],
       [0.55798992, 0.23662286, 0.97087511, 0.49941782],
       [0.02258435, 0.78058953, 0.35956656, 0.78162099]])

In [ ]:
# choose()

In [70]:
zx = random.choice([1, 2, 3, 4, 5, 6])

In [71]:
zx

3

In [74]:
zx = random.choice([1, 2, 3, 4, 5, 6], size = (5, 6))

In [75]:
zx

array([[4, 2, 3, 3, 3, 3],
       [6, 6, 1, 2, 4, 1],
       [6, 1, 5, 5, 5, 4],
       [6, 5, 1, 2, 4, 6],
       [3, 3, 3, 1, 2, 1]])

In [ ]:
# shuffle

In [76]:
zx = np.arange(2, 10)

In [80]:
zx

array([3, 4, 5, 2, 9, 8, 7, 6])

In [81]:
random.shuffle(zx)

In [82]:
zx

array([8, 5, 9, 2, 6, 4, 3, 7])

In [ ]:

random
randint
rand
arange
choice
shuffle
