# Reshape in Numpy

In [1]:
import numpy as np

In [6]:
arr = np.array([12, 43, 5, 56, 23, 67, 20, 100, 34, 10])

In [7]:
arr.shape

(10,)

In [8]:
len(arr)

10

In [9]:
arr.ndim

1

In [ ]:
# reshape

# 1d to 2d

In [12]:
xyz = arr.reshape(5, 2)

In [14]:
xyz

array([[ 12,  43],
       [  5,  56],
       [ 23,  67],
       [ 20, 100],
       [ 34,  10]])

In [20]:
arr = np.array([12, 43, 5, 56, 23, 67, 20, 100, 56, 34, 23, 11, 56, 34, 100])

In [21]:
len(arr)

15

In [22]:
c = arr.reshape(5, 3)

In [23]:
c

array([[ 12,  43,   5],
       [ 56,  23,  67],
       [ 20, 100,  56],
       [ 34,  23,  11],
       [ 56,  34, 100]])

In [28]:
arr = np.array([12, 43, 5, 56, 23, 67, 20, 100, 34, 10, 10, 100])

In [33]:
cy = arr.reshape(4, -1)

In [34]:
cy

array([[ 12,  43,   5],
       [ 56,  23,  67],
       [ 20, 100,  34],
       [ 10,  10, 100]])

In [37]:
zx = arr.reshape(-1, 4)

In [38]:
zx

array([[ 12,  43,   5,  56],
       [ 23,  67,  20, 100],
       [ 34,  10,  10, 100]])

# 1d to 3d

In [27]:
arr = np.array([12, 43, 5, 56, 23, 67, 20, 100, 34, 10, 10, 100])

In [25]:
len(arr)

12

In [39]:
xy = arr.reshape(2, 3, 2)

In [40]:
xy

array([[[ 12,  43],
        [  5,  56],
        [ 23,  67]],

       [[ 20, 100],
        [ 34,  10],
        [ 10, 100]]])

In [43]:
xy.shape

(2, 3, 2)

In [44]:
xy.ndim

3

# 2d to 1d

In [63]:
zx = np.array([[12, 45, 34, 12, 43 ,100], [56, 34, 2, 67, 34, 23]])

In [64]:
zx

array([[ 12,  45,  34,  12,  43, 100],
       [ 56,  34,   2,  67,  34,  23]])

In [65]:
zx.ndim

2

In [69]:
xyz = zx.reshape(12)

In [70]:
xyz

array([ 12,  45,  34,  12,  43, 100,  56,  34,   2,  67,  34,  23])

In [71]:
xyz1 = zx.reshape(-1)

In [72]:
xyz1

array([ 12,  45,  34,  12,  43, 100,  56,  34,   2,  67,  34,  23])

# 3d to 1d

In [102]:
zx = np.array([[[[[12, 45, 34, 12, 43], [56, 34, 2, 67, 34]], [[34, 23, 12, 34, 2], [34, 45, 23, 12, 12]]]]])

In [103]:
zx.ndim

5

In [104]:
zx.shape

(1, 1, 2, 2, 5)

In [105]:
zx

array([[[[[12, 45, 34, 12, 43],
          [56, 34,  2, 67, 34]],

         [[34, 23, 12, 34,  2],
          [34, 45, 23, 12, 12]]]]])

In [106]:
kl = zx.reshape(-1)

In [107]:
kl.shape

(20,)

In [108]:
kl.ndim

1

In [109]:
kl

array([12, 45, 34, 12, 43, 56, 34,  2, 67, 34, 34, 23, 12, 34,  2, 34, 45,
       23, 12, 12])

In [110]:
# zx.reshape(, -1)

In [ ]:
random