In [3]:
print("hello wolrd")

hello wolrd


In [4]:
a = 10

In [5]:
print(a)

10


In [6]:
a

10

In [7]:
b = 20

In [8]:
c = a + b


In [9]:
c

30

In [10]:
a = 300
b = 400
c = a + b

In [11]:
c

700

# Start Numpy

In [ ]:
# Numpy => 2005


In [ ]:
# array []

In [12]:
# list[]

lst = [10, 45, 67, 34, 56, 34, "hlo", "car", True]

In [ ]:
# numpy ====>  arrays
[
    numarical Python.

In [13]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [16]:
import numpy as np

In [ ]:
ndarray => those objects which are making using array method is called ndarray.

n dimetional arrays

In [17]:
arr = np.array(12)

In [18]:
arr

array(12)

In [19]:
type(arr)

numpy.ndarray

In [ ]:
ndim attribute: to check the demisonnksnsaksb of an array....

In [20]:
arr1 = np.array(100)

In [21]:
arr1.ndim

0

In [22]:
arr2 = np.array([12, 10, 56, 34, 100])

In [23]:
arr2

array([ 12,  10,  56,  34, 100])

In [24]:
arr2.ndim

1

In [31]:
arrx = np.array([[12, 56, 334], [34, 56, 23], [34, 56, 223]])

In [32]:
arrx

array([[ 12,  56, 334],
       [ 34,  56,  23],
       [ 34,  56, 223]])

In [33]:
arrx.ndim

2

In [40]:
arr3d = np.array([[[12, 34, 45], [45, 34, 56]], [[45, 67, 34], [67, 45, 34]]])


In [41]:
arr3d

array([[[12, 34, 45],
        [45, 34, 56]],

       [[45, 67, 34],
        [67, 45, 34]]])

In [42]:
arr3d.ndim

3

In [43]:
xyz = np.array([[[[[5]]]]])

In [44]:
xyz.ndim

5

In [45]:
# shape => 

In [46]:
arr2 = np.array([12, 10, 56, 34, 100])

In [47]:
arr2.shape

(5,)

In [48]:
arrx = np.array([[12, 56, 334], [34, 56, 223]])

In [49]:
arrx.shape

(2, 3)

In [50]:
arrx

array([[ 12,  56, 334],
       [ 34,  56, 223]])

In [51]:
arr3d = np.array([[[12, 34, 45], [45, 34, 56]], [[45, 67, 34], [67, 45, 34]]])


In [52]:
arr3d.shape

(2, 2, 3)

In [53]:
arr3d

array([[[12, 34, 45],
        [45, 34, 56]],

       [[45, 67, 34],
        [67, 45, 34]]])

In [54]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [56]:
help(np.shape)

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [57]:
# indexing, slicing

arr3d = np.array([[[12, 34, 45], [45, 34, 56]], [[45, 67, 34], [67, 45, 34]]])


In [58]:
arr3d[7]

IndexError: index 7 is out of bounds for axis 0 with size 2

In [61]:
zx = [[12, 45, 67, 45, 3,4, 23], 56, [67, 45, 34, 23, 45, 100]]

In [62]:
zx[1]

56

In [64]:
zx[2][-1]

100