In [1]:
import numpy as np

In [2]:
zx = np.array([12, 34, 23, 12, 34, 67, 45, 67, 34 ,100])

In [3]:
zx

array([ 12,  34,  23,  12,  34,  67,  45,  67,  34, 100])

In [4]:
zx[2] = 100
zx[3] = 1000

In [5]:
zx

array([  12,   34,  100, 1000,   34,   67,   45,   67,   34,  100])

In [6]:
b = np.array([12, 34, 23, 12, 34, 67, 45, 67, 34 ,100])

In [7]:
b[[2, 3]] = [20000, 4000] 

In [8]:
b

array([   12,    34, 20000,  4000,    34,    67,    45,    67,    34,
         100])

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [10]:
indexes = [2, -2, 4]

In [11]:
chnage_elemets = [20, 100, 500]

In [12]:
x[indexes] = chnage_elemets

In [13]:
x

array([  1,   2,  20,   4, 500,   6,   7,   8, 100,  10])

In [ ]:
# unique()  => help us to get unique elements only from a ndarray.

In [14]:
pq = np.array([12, 34, 1, 1, 2, 3, 12, 56, 34, 12, 67, 23, 1, 21, 12, 100])

In [15]:
pq

array([ 12,  34,   1,   1,   2,   3,  12,  56,  34,  12,  67,  23,   1,
        21,  12, 100])

In [16]:
y = np.unique(pq)

In [17]:
y

array([  1,   2,   3,  12,  21,  23,  34,  56,  67, 100])

# resize()

In [24]:
arr = np.array([34, 23, 12, 45, 10, 100])

In [25]:
we = np.resize(arr, (5, 8))

In [26]:
we

array([[ 34,  23,  12,  45,  10, 100,  34,  23],
       [ 12,  45,  10, 100,  34,  23,  12,  45],
       [ 10, 100,  34,  23,  12,  45,  10, 100],
       [ 34,  23,  12,  45,  10, 100,  34,  23],
       [ 12,  45,  10, 100,  34,  23,  12,  45]])

In [35]:
# trim_zero()

In [45]:
a = np.array([0, 0, 0, 7, 5, 3, 0, 8, 0, 0, 0, 0, 12, 4, 4, 1, 0, 0, 0])

In [46]:
x = np.trim_zeros(a)

In [47]:
x

array([ 7,  5,  3,  0,  8,  0,  0,  0,  0, 12,  4,  4,  1])

In [ ]:
# fency indexing : mask

In [49]:
# True False

In [55]:
zx = np.arange(1, 17)

In [56]:
zx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [59]:
zx = zx.reshape(4, 4)

In [61]:
zx

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
zx % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [62]:
zx == 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [68]:
zx

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
p = zx % 2 == 0

In [67]:
zx[p]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [69]:
zeros = np.array([12, 4, 0, 5, 0, 4, 0, 5, 3, 0, 4, 8, 0])

In [70]:
zeros

array([12,  4,  0,  5,  0,  4,  0,  5,  3,  0,  4,  8,  0])

In [78]:
x = (zeros != 0) | (zeros == 3)

In [74]:
zeros[x]

array([12,  4,  5,  4,  5,  3,  4,  8])

In [ ]:
1 ---- 100

devisbile by 3 and devisible by 5